init:
  # Reset dynamic port range from AppVeyor setting (1025-65535) to Windows default (49152-65535),
  # to prevent conflicts with ANCM random ports (1025-48000).
  - netsh int ipv4 show dynamicport tcp
  - netsh int ipv4 set dynamic tcp start=49152 num=16384
  - netsh int ipv4 show dynamicport tcp

  - git config --global core.autocrlf true
branches:
  only:
    - dev
    - /^release\/.*$/
    - /^(.*\/)?ci-.*$/
install:
  - ps: .\tools\update_schema.ps1
  - git submodule update --init --recursive
  - net start w3svc
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
