init:
- git config --global core.autocrlf true
install:
  - ps: Install-Product node 8 x64
branches:
  only:
  - dev
  - feature/0.1.0
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: 'off'
deploy: 'off'
os: Visual Studio 2017 Preview
build_script:
  - build.cmd /p:SkipTests=true /p:BlazorOutputStatistics=true
before_test:
  - choco install googlechrome --ignore-checksum
  - npm install -g selenium-standalone
  - selenium-standalone install --singleDriverInstall=chrome
  - ps: $SeleniumProcess = Start-Process "selenium-standalone" -ArgumentList "start" -PassThru
test_script:
  - build.cmd /t:Test /p:BlazorAllTests=true /p:BlazorOutputStatistics=true
after_test:
  - ps: Stop-Process -Id $SeleniumProcess.Id
