init:
  - git config --global core.autocrlf true
environment:
  AUTOBAHN_SUITES_LOG: 1
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
    - /release\/.*/
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017
