init:
- git config --global core.autocrlf true
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: 'off'
deploy: 'off'
os: Visual Studio 2017 Preview

# Everything above here copied from the ASP.NET Core configurations
build:
  project: Blazor.sln