language: csharp
sudo: required
dist: trusty
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
addons:
  apt:
    packages:
    - libunwind8
  chrome: stable
mono: none
os:
- linux
- osx
osx_image: xcode8.2
branches:
  only:
  - master
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
before_install:
- if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  /usr/local/lib/; fi
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10.13.0
  - nvm use 10.13.0
  - npm install -g selenium-standalone
  - selenium-standalone install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TEST_CHROME_BINARY=`which google-chrome-stable`; fi
  - export DOTNET_INSTALL_DIR="$PWD/.dotnet"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - ./build.sh --ci /p:SkipTests=true /p:BlazorOutputStatistics=true
  - selenium-standalone start &
  - ./build.sh --ci /t:Test /p:BlazorAllTests=true
