name: Backport PR to branch
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
      pr_description_template: |
        Backport of #%source_pr_number% to %target_branch%

        /cc %cc_users%

        # %source_pr_title%

        Summary of the changes (Less than 80 chars)

        ## Description

        {Detail}

        Fixes #{bug number} (in this specific format)

        ## Customer Impact

        {Justification}

        ## Regression?

        - [ ] Yes
        - [ ] No

        [If yes, specify the version the behavior has regressed from]

        ## Risk

        - [ ] High
        - [ ] Medium
        - [ ] Low

        [Justify the selection above]

        ## Verification

        - [ ] Manual (required)
        - [ ] Automated

        ## Packaging changes reviewed?

        - [ ] Yes
        - [ ] No
        - [ ] N/A

        ----

        ## When servicing release/2.1

        - [ ] Make necessary changes in eng/PatchConfig.props
