name: Run PR Benchmarks
on:
  issue_comment:
    types: [created]

jobs:
  benchmark:
    # Comments can be triggered on issues and prs, ensure this is a PR
    if: github.repository == 'dotnet/aspnetcore' && github.event.issue.pull_request != '' && contains(github.event.comment.body, '/benchmark')
    name: Benchmark PR
    runs-on: ubuntu-latest
    steps:
    - name: Extract benchmark argument
      uses: actions/github-script@v4
      id: benchmark-argument
      with:
        result-encoding: string
        script: |

          // Documents all available commands
          const availableProfiles = {
            "kestrel": "Runs Plaintext on Kestrel changes.",
            "mvc": "Runs Plaintext on Mvc changes.",
            "yarp": "Runs Yarp on Kestrel changes.",
          };

          // Verify the user is a collaborator

          const repo_owner = context.payload.repository.owner.login;
          const repo_name = context.payload.repository.name;
          const comment_user = context.payload.comment.user.login;

          try {
            var membership = await github.repos.checkCollaborator({
              owner: repo_owner,
              repo: repo_name,
              username: comment_user
            });
          } catch (error) {
            var message = `Error: @${comment_user} is not a repo collaborator, benchmarking is not allowed.`;

            await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

            throw message;
          }

          core.info(`Verified ${comment_user} is a repo collaborator.`);

          // Verify this action is and PR comment

          if (context.eventName !== "issue_comment") throw "Error: This action only works on issue_comment events.";

          // Verify command arguments

          // Extract the benchmark arguments from the trigger phrase containing these characters: a-z, A-Z, digits, forward slash, dot, hyphen, underscore
          const regex = /\/benchmark ([a-zA-Z\d\/\.\-\_]+)/;
          const arguments = regex.exec(context.payload.comment.body);

          // Generate help text with all available commands
          if (arguments == null || arguments.length < 2 || !availableProfiles.hasOwnProperty(arguments[1])) {
              var body = 'The `/benchmark` command accepts these profiles:\n';
              for (var key in availableProfiles) {
                body += `- \`/benchmark ${key}\`: ${availableProfiles[key]}\n`;
              }

              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });

              throw "Error: Invalid arguments, workflow stopped.";
          }

          const profile = arguments[1];
          core.info(`Profile: ${profile}`);

          const start_body = `Started benchmarking https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: start_body
          });

          return profile;

    - name: Install crank
      run: |
        dotnet tool install Microsoft.Crank.Controller --version "0.2.0-*" --global

    - name: Checkout
      run: |
        rm -rf aspnetcore
        git clone --recursive ${{ github.event.repository.clone_url }} aspnetcore

    - name: Benchmark Kestrel
      working-directory: ./aspnetcore
      env:
        AZURE_RELAY: ${{ secrets.AZURE_RELAY }}
      if: ${{ steps.benchmark-argument.outputs.result == 'kestrel' }}
      run: |
        CRANK_PROFILE="aspnet-perf-lin-relay"
        CRANK_CONFIGS="--config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true "
        CRANK_ARGUMENTS="--config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --scenario plaintext --application.framework net6.0 --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel/release/net7.0/"

        git checkout $GITHUB_BASE_REF

        echo "Building Kestrel"
        ./src/Servers/Kestrel/build.sh -c release

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/base.json" $CRANK_ARGUMENTS

        git fetch origin pull/${{ github.event.issue.number }}/head
        git config --global user.name "user"
        git config --global user.email "user@company.com"
        git merge FETCH_HEAD

        echo "Building Kestrel"
        ./src/Servers/Kestrel/build.sh -c release

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/head.json" $CRANK_ARGUMENTS

        cd $GITHUB_WORKSPACE
        echo "Arguments:"$'\n```\n'$"$CRANK_ARGUMENTS"$'\n```\n' >> results.txt
        echo "Results:"$'\n```\n' >> results.txt
        crank compare base.json head.json >> results.txt
        echo $'\n```\n' >> results.txt

        cat results.txt

    - name: Benchmark Yarp
      working-directory: ./aspnetcore
      env:
        AZURE_RELAY: ${{ secrets.AZURE_RELAY }}
      if: ${{ steps.benchmark-argument.outputs.result == 'yarp' }}
      run: |
        CRANK_PROFILE="aspnet-perf-lin-relay"
        CRANK_CONFIGS="--config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true "
        CRANK_ARGUMENTS="--config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/proxy.benchmarks.yml --scenario proxy-yarp --application.framework net6.0 --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel/release/net7.0/"

        git checkout $GITHUB_BASE_REF

        echo "Building Kestrel"
        ./src/Servers/Kestrel/build.sh -c release

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/base.json" $CRANK_ARGUMENTS

        git fetch origin pull/${{ github.event.issue.number }}/head
        git config --global user.name "user"
        git config --global user.email "user@company.com"
        git merge FETCH_HEAD

        echo "Building Kestrel"
        ./src/Servers/Kestrel/build.sh -c release

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/head.json" $CRANK_ARGUMENTS

        cd $GITHUB_WORKSPACE
        echo "Arguments:"$'\n```\n'$"$CRANK_ARGUMENTS"$'\n```\n' >> results.txt
        echo "Results:"$'\n```\n' >> results.txt
        crank compare base.json head.json >> results.txt
        echo $'\n```\n' >> results.txt

        cat results.txt

    - name: Benchmark Mvc
      working-directory: ./aspnetcore
      env:
        AZURE_RELAY: ${{ secrets.AZURE_RELAY }}
      if: ${{ steps.benchmark-argument.outputs.result == 'mvc' }}
      run: |
        CRANK_PROFILE="aspnet-perf-lin-relay"
        CRANK_CONFIGS="--config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true "
        CRANK_ARGUMENTS="--config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --scenario mvc --application.framework net6.0 --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Mvc.IntegrationTests/release/net7.0/"

        git checkout $GITHUB_BASE_REF

        echo "Building Mvc"
        ./src/Mvc/build.sh -c release -NoBuildNodeJS

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/base.json" $CRANK_ARGUMENTS

        git fetch origin pull/${{ github.event.issue.number }}/head
        git config --global user.name "user"
        git config --global user.email "user@company.com"
        git merge FETCH_HEAD

        echo "Building Mvc"
        ./src/Mvc/build.sh -c release -NoBuildNodeJS

        crank $CRANK_CONFIGS --profile $CRANK_PROFILE --relay AZURE_RELAY --json "$GITHUB_WORKSPACE/head.json" $CRANK_ARGUMENTS

        cd $GITHUB_WORKSPACE
        echo "Arguments:"$'\n```\n'$"$CRANK_ARGUMENTS"$'\n```\n' >> results.txt
        echo "Results:"$'\n```\n' >> results.txt
        crank compare base.json head.json >> results.txt
        echo $'\n```\n' >> results.txt

        cat results.txt

    - name: Report results
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require("fs");
          const results = fs.readFileSync("results.txt", "utf8");

          await github.issues.createComment({
            issue_number: context.payload.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: results
          });
