name: "[Monthly] Schedule Browser-Testing Dependencies Update Issue"

on:
  schedule:
    # Runs on the first day of every month at midnight UTC
    - cron: '0 0 1 * *'
  workflow_dispatch: # for manual triggering

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # copilot can be assigned to the issue
      # https://cli.github.com/manual/gh_issue_create
      - name: Create Issue From Template
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --title "Request Browser-Testing Dependencies Update" \
            --body-file ".github/workflows/browsertesting-issue-body.md" \
            --assignee "@copilot"
